from enum import Enum


class Page(Enum):
    HAUPTMENUE = 0
    SICHTPRUEFUNG_AUSWAHL = 1
    SICHTPRUEFUNG_INFOS = 2
    SICHTPRUEFUNG_VORGABEN = 3
    SICHTPRUEFUNG_PRUEFABLAUF = 4
    SICHTPRUEFUNG_EIGENSCHAFT = 5
    SICHTPRUEFUNG_ZUSAMMENFASSUNG = 6
    PRUEFANWEISUNG_AUSWAHL = 7
    PRUEFANWEISUNG_INFOS = 8
    PRUEFANWEISUNG_VORGABEN = 9
    PRUEFANWEISUNG_PRUEFABLAUF = 10
    PRUEFANWEISUNG_TYPISCHE_MAENGEL = 11
    PRUEFANWEISUNG_EIGENSCHAFT = 12
    PRUEFANWEISUNG_ZUSAMMENFASSUNG = 13
    ERFOLGREICH_ABGESCHLOSSEN = 14